apiVersion: v2
name: product-chart
description: An product service

type: application

version: 0.1.0
appVersion: 0.1.0

dependencies:
  - name: postgresql
    version: 8.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - product-database
