apiVersion: v1
kind: ConfigMap
metadata:
  namespace: course-microservices
  name: hw2-service-config
data:
  jdbc-url: jdbc:h2:mem:testdb
  db-driver: org.h2.Driver
  db-platform: org.hibernate.dialect.H2Dialect
  h2-console-enabled: "true"
---
apiVersion: v1
kind: Secret
metadata:
  namespace: course-microservices
  name: hw2-service-secret
type: Opaque
data:
  db-login: c2E=
  db-password: ''
