apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-deployment-new
spec:
    replicas: 2
    selector:
       matchLabels:
          app: hello-py-app-new
    template:
       metadata:
          labels:
             app: hello-py-app-new
       spec:
          containers:
          - name: hello-py
            image: hello-py:v2
            ports:
              - name: web 
                containerPort: 80
