apiVersion: v1
kind: ConfigMap
metadata:
  name: hw2-service-config
data:
  jdbc-url: {{ .Values.externalDb.dbUrl }}
  db-driver: {{ .Values.externalDb.dbDriver }}
  db-platform: {{ .Values.externalDb.dbPlatform }}
  h2-console-enabled: {{ .Values.externalDb.devMode }}
---
apiVersion: v1
kind: Secret
metadata:
  name: hw2-service-secret
type: Opaque
data:
  db-login: {{ .Values.externalDb.dbUser }}
  db-password: {{ .Values.externalDb.dbPassword }}
