apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hw2-service.fullname" . }}
  labels:
    {{- include "hw2-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hw2-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hw2-service.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: {{ .Chart.Name }}-init
          image: busybox:1.28
          command: ['sh', '-c', "until nslookup postgres.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for postgres; sleep 2; done; sleep 10"]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/storage
              port: web
            initialDelaySeconds: 10
            periodSeconds: 15
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: PROM
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: hw2-service-config
                  key: jdbc-url
            - name: SPRING_DATASOURCE_DRIVERCLASSNAME
              valueFrom:
                configMapKeyRef:
                  name: hw2-service-config
                  key: db-driver
            - name: SPRING_JPA_DATABASE-PLATFORM
              valueFrom:
                configMapKeyRef:
                  name: hw2-service-config
                  key: db-platform
            - name: MANAGEMENT_ENDPOINT_HEALTH_SHOW-COMPONENTS
              value: always
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: health,prometheus
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
            #- name: MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES-HISTOGRAM_HTTP_SERVER_REQUESTS
            #  value: "true"

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hw2-service-secret
                  key: db-login
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hw2-service-secret
                  key: db-password

