apiVersion: skaffold/v2beta2
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: simple-app
    context: .
deploy:
  helm:
    releases:
    - name: simple-app
      chartPath: simple-app-chart
      skipBuildDependencies: false
      values:
        image: simple-app
