# Source: hello-chart/templates/initdb.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "initdb"
spec:
  template:
    metadata:
      name: "initdb"
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-db-ready
          image: postgres:latest
          env:
            - name: POSTGRES_HOST
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
          command:
            - sh
            - "-c"
            - |
              until pg_isready -h $POSTGRES_HOST  -p  $POSTGRES_PORT;
              do echo waiting for database; sleep 2; done;
      containers:
      - name: initdb
        env:
          - name: DATABASE_URI
            value: "postgresql://myuser:passwd@postgres:5432/myapp"
        image: postgres:latest
        command:
          - sh
          - "-c"
          - |
            psql $DATABASE_URI <<'EOF'
              create table client (id bigint primary key, name varchar);
              insert into client (id, name) values (1, 'Konstantin');
            EOF
  backoffLimit: 2
