replicaCount: 2

image:
  repository: kochnevd/course-microservices

service:
  type: NodePort
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: arch.homework
      paths:
        - path: /
          pathType: Prefix

externalDb:
  dbUrl: "jdbc:h2:mem:testdb"
  dbDriver: "org.h2.Driver"
  dbPlatform: "org.hibernate.dialect.H2Dialect"
  dbUser: "c2E="
  dbPassword: ''''''
  devMode: '"true"'

