apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-deployment
spec:
    replicas: 2
    selector:
       matchLabels:
          app: hello-py-app
    template:
       metadata:
          labels:
             app: hello-py-app
       spec:
          containers:
          - name: hello-py
            image: hello-py:v10
            env:
              - name: DATABASE_URI
                value: "postgresql+psycopg2://myuser:passwd@postgres:5432/myapp"
              - name: GREETING
                value: "Alloha"
            ports:
              - name: web 
                containerPort: 80
