replicaCount: 2

service:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
  externalTrafficPolicy:

enableAES: false

redis:
  create: true

authService:
  create: false

rateLimit:
  create: false
